name: flutter_widgets
description: A flutter application that explains flutter widgets with example.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2


flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
